# Единственный native dependency manifest; пути разрешаются от репозитория.
set(AZURPILOT_OPENCV_MANIFEST "${CMAKE_CURRENT_LIST_DIR}/../opencv.json")
file(READ "${AZURPILOT_OPENCV_MANIFEST}" AZURPILOT_OPENCV_JSON)
foreach(field IN ITEMS version url sha256 archiveRoot cmakeDir runtimeDir)
  string(JSON value ERROR_VARIABLE json_error GET "${AZURPILOT_OPENCV_JSON}" "${field}")
  if(json_error OR value STREQUAL "")
    message(FATAL_ERROR "В native/opencv.json отсутствует корректное поле ${field}: ${json_error}")
  endif()
  set("AZURPILOT_OPENCV_${field}" "${value}")
endforeach()
if(NOT AZURPILOT_OPENCV_version MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
  message(FATAL_ERROR "Некорректная версия OpenCV в native/opencv.json: ${AZURPILOT_OPENCV_version}")
endif()
string(LENGTH "${AZURPILOT_OPENCV_sha256}" hash_length)
if(NOT hash_length EQUAL 64 OR NOT AZURPILOT_OPENCV_sha256 MATCHES "^[0-9A-Fa-f]+$")
  message(FATAL_ERROR "native/opencv.json: sha256 должен содержать ровно 64 шестнадцатеричных символа.")
endif()
if(NOT AZURPILOT_OPENCV_url MATCHES "^https://")
  message(FATAL_ERROR "native/opencv.json: url должен использовать HTTPS.")
endif()
foreach(field IN ITEMS archiveRoot cmakeDir runtimeDir)
  set(value "${AZURPILOT_OPENCV_${field}}")
  if(IS_ABSOLUTE "${value}" OR value MATCHES "(^|[/\\\\])\\.\\.([/\\\\]|$)" OR value MATCHES ":|;")
    message(FATAL_ERROR "native/opencv.json: ${field} должен быть относительным путём внутри пакета: ${value}")
  endif()
endforeach()

set(AZURPILOT_OPENCV_VERSION "${AZURPILOT_OPENCV_version}")
cmake_path(GET AZURPILOT_OPENCV_url FILENAME archive_name)
get_filename_component(repository_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(download_dir "${repository_root}/artifacts/downloads")
set(archive_file "${download_dir}/${archive_name}")
set(extract_dir "${repository_root}/artifacts/opencv/${AZURPILOT_OPENCV_VERSION}")
set(OpenCV_DIR "${extract_dir}/${AZURPILOT_OPENCV_cmakeDir}")
set(AZURPILOT_OPENCV_RUNTIME_DIR "${extract_dir}/${AZURPILOT_OPENCV_runtimeDir}")

file(MAKE_DIRECTORY "${download_dir}")
# Разные configure не могут одновременно получать или распаковывать один пакет.
file(LOCK "${download_dir}/opencv.lock" GUARD FILE TIMEOUT 300)
if(NOT EXISTS "${archive_file}")
  message(STATUS "Получение OpenCV ${AZURPILOT_OPENCV_VERSION}: ${AZURPILOT_OPENCV_url}")
  file(DOWNLOAD "${AZURPILOT_OPENCV_url}" "${archive_file}.partial"
    TLS_VERIFY ON STATUS download_status INACTIVITY_TIMEOUT 120)
  list(GET download_status 0 download_code)
  if(NOT download_code EQUAL 0)
    file(REMOVE "${archive_file}.partial")
    message(FATAL_ERROR "Не удалось скачать OpenCV из native/opencv.json: ${download_status}")
  endif()
  file(SHA256 "${archive_file}.partial" actual_hash)
  string(TOLOWER "${AZURPILOT_OPENCV_sha256}" expected_hash)
  if(NOT actual_hash STREQUAL expected_hash)
    file(REMOVE "${archive_file}.partial")
    message(FATAL_ERROR "SHA256 скачанного OpenCV не совпал: ожидалось ${expected_hash}; получено ${actual_hash}. Распаковка не выполняется.")
  endif()
  file(RENAME "${archive_file}.partial" "${archive_file}")
endif()

# Кэшированный архив проходит ту же проверку, что и новая загрузка.
file(SHA256 "${archive_file}" actual_hash)
string(TOLOWER "${AZURPILOT_OPENCV_sha256}" expected_hash)
if(NOT actual_hash STREQUAL expected_hash)
  message(FATAL_ERROR "SHA256 OpenCV не совпал: ожидалось ${expected_hash}; получено ${actual_hash}. Удалите повреждённый ${archive_file} и повторите configure; распаковка не выполняется.")
endif()
set(extract_stamp "${extract_dir}/.azurpilot-sha256")
set(extracted_hash "")
if(EXISTS "${extract_stamp}")
  file(READ "${extract_stamp}" extracted_hash)
endif()
if(NOT extracted_hash STREQUAL expected_hash OR
   NOT EXISTS "${OpenCV_DIR}/OpenCVConfig.cmake" OR
   NOT IS_DIRECTORY "${AZURPILOT_OPENCV_RUNTIME_DIR}")
  # Windows bsdtar умеет распаковывать официальный самораспаковывающийся EXE.
  find_program(AZURPILOT_ARCHIVE_TOOL NAMES tar.exe REQUIRED)
  # Повторная попытка не должна смешивать пакет с остатками прерванной распаковки.
  file(REMOVE_RECURSE "${extract_dir}")
  file(MAKE_DIRECTORY "${extract_dir}")
  execute_process(COMMAND "${AZURPILOT_ARCHIVE_TOOL}" -x -f "${archive_file}" -C "${extract_dir}"
    RESULT_VARIABLE extract_code ERROR_VARIABLE extract_error)
  if(NOT extract_code EQUAL 0)
    message(FATAL_ERROR "Распаковка OpenCV завершилась с кодом ${extract_code}: ${extract_error}")
  endif()
endif()
if(NOT IS_DIRECTORY "${extract_dir}/${AZURPILOT_OPENCV_archiveRoot}" OR
   NOT EXISTS "${OpenCV_DIR}/OpenCVConfig.cmake" OR
   NOT IS_DIRECTORY "${AZURPILOT_OPENCV_RUNTIME_DIR}")
  message(FATAL_ERROR "Layout полученного OpenCV не соответствует native/opencv.json: ${extract_dir}")
endif()
if(NOT extracted_hash STREQUAL expected_hash)
  file(WRITE "${extract_stamp}" "${expected_hash}")
endif()
message(STATUS "OpenCV ${AZURPILOT_OPENCV_VERSION}: SHA256 проверен; OpenCV_DIR=${OpenCV_DIR}")
