# Узкая build-цель: точные runtime-файлы из native и импортированного OpenCV target.
cmake_policy(SET CMP0057 NEW)
if(NOT EXISTS "${NATIVE_FILE}" OR NOT EXISTS "${OPENCV_FILE}")
  message(FATAL_ERROR "Staging native runtime невозможен: отсутствует ${NATIVE_FILE} или ${OPENCV_FILE}.")
endif()
get_filename_component(opencv_directory "${OPENCV_FILE}" DIRECTORY)
cmake_path(NORMAL_PATH opencv_directory)
cmake_path(NORMAL_PATH OPENCV_RUNTIME_DIR)
if(NOT opencv_directory STREQUAL OPENCV_RUNTIME_DIR)
  message(FATAL_ERROR "OpenCV target использует runtime вне native/opencv.json: ${OPENCV_FILE}")
endif()
file(MAKE_DIRECTORY "${RUNTIME_DIR}")
set(runtime_files "${NATIVE_FILE}" "${OPENCV_FILE}")
if(EXISTS "${NATIVE_PDB}")
  list(APPEND runtime_files "${NATIVE_PDB}")
endif()
set(expected_names "")
foreach(source IN LISTS runtime_files)
  get_filename_component(name "${source}" NAME)
  list(APPEND expected_names "${name}")
  file(COPY_FILE "${source}" "${RUNTIME_DIR}/${name}" ONLY_IF_DIFFERENT)
endforeach()
# Старые DLL/PDB не переживают смену dependency pin; native test артефакты сюда не входят.
file(GLOB staged_files "${RUNTIME_DIR}/*.dll" "${RUNTIME_DIR}/*.pdb")
foreach(staged_file IN LISTS staged_files)
  get_filename_component(name "${staged_file}" NAME)
  if(NOT name IN_LIST expected_names)
    file(REMOVE "${staged_file}")
  endif()
endforeach()
get_filename_component(native_directory "${NATIVE_FILE}" DIRECTORY)
get_filename_component(opencv_name "${OPENCV_FILE}" NAME)
file(COPY_FILE "${OPENCV_FILE}" "${native_directory}/${opencv_name}" ONLY_IF_DIFFERENT)
